import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sundar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div className={inter.className}>{children}</div>
    
  );
}
